media:
  input: "index_files"
  output: "/index_files"

content:
  - name: pages
    label: "Pages"
    type: file
    files:
      - name: home
        label: "Home (index.html)"
        path: "index.html"
        fields:
          - name: body
            label: "Page HTML"
            type: rich-text
      - name: bio
        label: "Bio Page"
        path: "bio.html"
        fields:
          - name: body
            label: "Page HTML"
            type: rich-text
      - name: contact
        label: "Contact Page"
        path: "contact.html"
        fields:
          - name: body
            label: "Page HTML"
            type: rich-text
